import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  BeforeInsert,
  BeforeUpdate,
  ManyToMany,
  JoinTable,
  Index,
} from 'typeorm';
import * as bcrypt from 'bcrypt';
import { Role } from '../../rbac/entities/role.entity';

/**
 * User entity representing a user record in the database
 * Maps to 'users' table in PostgreSQL
 */
@Entity('users')
@Index(['email']) // Index for faster email lookups during auth
@Index(['isActive']) // Index for filtering active users
@Index(['createdAt']) // Index for sorting by creation date
export class User {
  /**
   * Unique identifier (UUID v4)
   * Auto-generated on creation
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * User's email address - must be unique across all users
   * Used for authentication and communication
   */
  @Column({ unique: true })
  email: string;

  /**
   * User's first name
   * Length: 2-50 characters
   */
  @Column()
  firstName: string;

  /**
   * User's last name
   * Length: 2-50 characters
   */
  @Column()
  lastName: string;

  /**
   * User's hashed password
   * Stored securely using bcrypt hashing
   * Never returned in API responses
   */
  @Column({ select: false })
  password: string;

  /**
   * Indicates if the user account is active
   * Defaults to true on creation
   */
  @Column({ default: true })
  isActive: boolean;

  /**
   * Indicates if the user's email has been verified
   * Defaults to false on creation
   */
  @Column({ default: false })
  isEmailVerified: boolean;

  /**
   * Token for email verification
   * Generated when user registers
   */
  @Column({ nullable: true, select: false })
  emailVerificationToken: string;

  /**
   * Expiry date for email verification token
   */
  @Column({ nullable: true, select: false })
  emailVerificationExpires: Date;

  /**
   * Token for password reset
   * Generated when user requests password reset
   */
  @Column({ nullable: true, select: false })
  passwordResetToken: string;

  /**
   * Expiry date for password reset token
   */
  @Column({ nullable: true, select: false })
  passwordResetExpires: Date;

  /**
   * User roles for RBAC
   * Many-to-many relationship with Role entity
   */
  @ManyToMany(() => Role, (role) => role.users, { eager: true })
  @JoinTable({
    name: 'user_roles',
    joinColumn: { name: 'userId', referencedColumnName: 'id' },
    inverseJoinColumn: { name: 'roleId', referencedColumnName: 'id' },
  })
  roles: Role[];

  /**
   * Timestamp when the user was created
   * Auto-generated by database
   */
  @CreateDateColumn()
  createdAt: Date;

  /**
   * Timestamp when the user was last updated
   * Auto-updated by database on changes
   */
  @UpdateDateColumn()
  updatedAt: Date;

  /**
   * Hash password before inserting into database
   * Uses bcrypt with salt rounds of 10
   */
  @BeforeInsert()
  async hashPasswordBeforeInsert() {
    if (this.password) {
      this.password = await bcrypt.hash(this.password, 10);
    }
  }

  /**
   * Hash password before updating in database (if password changed)
   * Uses bcrypt with salt rounds of 10
   */
  @BeforeUpdate()
  async hashPasswordBeforeUpdate() {
    if (this.password) {
      this.password = await bcrypt.hash(this.password, 10);
    }
  }

  /**
   * Compare provided password with stored hashed password
   *
   * @param password - Plain text password to verify
   * @returns Promise<boolean> - True if password matches, false otherwise
   */
  async comparePassword(password: string): Promise<boolean> {
    return bcrypt.compare(password, this.password);
  }
}
